export default [
  {
    path: '/',
    name: 'Anasayfa',
    icon: 'fa-home',
    uniq_id: 'home',
  },
  {
    path: '/quick-sale',
    name: 'Hızlı Satış',
    icon: 'fa-bolt',
    uniq_id: 'quick-sale',
  },
  {
    path: '/invoices',
    name: 'Faturalarım',
    icon: 'fa-file-invoice',
    uniq_id: 'invoices',
  },
  {
    path: '/account-transactions',
    name: 'Hesap Hareketleri',
    icon: 'fa-exchange-alt',
    uniq_id: 'account-transactions',
  },
  {
    path: '/income-expense',
    name: 'Gelir-Gider Takibi',
    icon: 'fa-chart-line',
    uniq_id: 'income-expense',
  },
  {
    path: '/cash-register',
    name: 'Kasa',
    icon: 'fa-cash-register',
    uniq_id: 'cash-register',
  },
  {
    path: '/contacts',
    name: 'Rehber',
    icon: 'fa-address-book',
    uniq_id: 'contacts',
  },
  {
    path: '/reports',
    name: 'Raporlar',
    icon: 'fa-chart-pie',
    uniq_id: 'reports',
  },
  {
    path: '/customers',
    name: 'Müşteriler',
    icon: 'fa-users',
    uniq_id: 'customers',
  },
  {
    path: '/suppliers',
    name: 'Tedarikçiler',
    icon: 'fa-truck',
    uniq_id: 'suppliers',
  },
  {
    path: '/inventory',
    name: 'Stok Yönetimi',
    icon: 'fa-boxes',
    uniq_id: 'inventory',
  },
  {
    path: '/invoice-create',
    name: 'Fatura Oluştur',
    icon: 'fa-file-invoice-dollar',
    uniq_id: 'invoice-create',
  },
  {
    path: '/payments',
    name: 'Ödemeler',
    icon: 'fa-credit-card',
    uniq_id: 'payments',
  },
  {
    path: '/taxes',
    name: 'Vergiler',
    icon: 'fa-file-invoice',
    uniq_id: 'taxes',
  },
  {
    path: '/notifications',
    name: 'Bildirimler',
    icon: 'fa-bell',
    uniq_id: 'notifications',
  },

  // {
  //   path: '/checks-promissory',
  //   name: 'Çek & Senet Takibi',
  //   icon: 'fa-money-check-alt',
  //   uniq_id: 'checks-promissory',
  // },
  // {
  //   path: '/bank-reconciliation',
  //   name: 'Banka Mutabakatı',
  //   icon: 'fa-university',
  //   uniq_id: 'bank-reconciliation',
  // },
  // {
  //   path: '/multi-currency',
  //   name: 'Çoklu Döviz',
  //   icon: 'fa-money-bill-wave',
  //   uniq_id: 'multi-currency',
  // },
  // {
  //   path: '/multi-branch',
  //   name: 'Şube Yönetimi',
  //   icon: 'fa-building',
  //   uniq_id: 'multi-branch',
  // },
  // {
  //   path: '/accounting-entries',
  //   name: 'Yevmiye & Defterler',
  //   icon: 'fa-book',
  //   uniq_id: 'accounting-entries',
  // },
  // {
  //   path: '/payroll',
  //   name: 'Personel & Bordro',
  //   icon: 'fa-user-tie',
  //   uniq_id: 'payroll',
  // },
  // {
  //   path: '/project-costing',
  //   name: 'Proje & Maliyet Takibi',
  //   icon: 'fa-project-diagram',
  //   uniq_id: 'project-costing',
  // },
  {
    path: '/reminders',
    name: 'Hatırlatıcılar',
    icon: 'fa-bell',
    uniq_id: 'reminders',
  },
  {
    path: '/user-management',
    name: 'Kullanıcı Yönetimi',
    icon: 'fa-users-cog',
    uniq_id: 'user-management',
  },
  {
    path: '/settings',
    name: 'Ayarlar',
    icon: 'fa-cogs',
    uniq_id: 'settings',
  },
]
